<table>
    <tr>
        <th>Firstname</th>
        <th>Lastname</th>
        <th><a href="/user/add" class="btn btn-default">Add user</a></th>
    </tr>
    <?php foreach ($users as $user) : ?>
    <tr>
        <td><?= $user->getFirstname() ?></td>
        <td><?= $user->getLastname() ?></td>
        <td><a href="/user/edit/<?= $user->getId() ?>" class="btn btn-info">Edit</a></td>
    </tr>
    <?php endforeach; ?>
</table>